[package]
org = "tikiricare"
name = "tikiricare_backend"
version = "1.0.0"

[build-options]
observabilityIncluded = true

[dependencies]
"ballerina/http" = "^2.8.0"
"ballerina/jwt" = "^2.8.0"
"ballerina/time" = "^2.8.0"
"ballerina/log" = "^2.8.0"
"ballerina/uuid" = "^2.8.0"
"ballerina/io" = "^2.8.0"
"ballerinax/mongodb" = "^5.1.0"


